In [1]:
import pandas as pd
import numpy as np

In [2]:
veriler=np.random.randint(1,50,([4,5]))

In [3]:
veriler

array([[46, 12, 10, 30, 28],
       [29, 48, 30, 40,  7],
       [ 3,  9, 44,  5,  9],
       [29, 38, 46, 36, 15]])

In [7]:
df=pd.DataFrame(veriler)# veriler dizisnden olşuan df adıdan bir dataframe oluşturduk

In [8]:
df

    0   1   2   3   4
0  46  12  10  30  28
1  29  48  30  40   7
2   3   9  44   5   9
3  29  38  46  36  15

In [10]:
df=pd.DataFrame(veriler,columns=["s1","s2","s3","s4","s5",],index=["st1","st2","st3","st4",])
#colums ile sütun isimleri,index ile satırları isimleri deeğiştirilir
df

     s1  s2  s3  s4  s5
st1  46  12  10  30  28
st2  29  48  30  40   7
st3   3   9  44   5   9
st4  29  38  46  36  15

In [11]:
veriler=[["nazlıcan","karadeniz",16],["batuhan","karadeniz",21]]

In [19]:
df=pd.DataFrame(veriler,columns=["isim","soyad","yaş"],index=["öğr1","öğr2"])

In [20]:
df

          isim      soyad  yaş
öğr1  nazlıcan  karadeniz   16
öğr2   batuhan  karadeniz   21

In [25]:
df=pd.read_csv("diabetes_data_upload.csv")
df

,Age,Gender,Polyuria,Polydipsia,sudden weight loss,weakness,Polyphagia,Genital thrush,visual blurring,Itching,Irritability,delayed healing,partial paresis,muscle stiffness,Alopecia,Obesity,class
0,40,Male,No,Yes,No,Yes,No,No,No,Yes,No,Yes,No,Yes,Yes,Yes,Positive
1,58,Male,No,No,No,Yes,No,No,Yes,No,No,No,Yes,No,Yes,No,Positive
2,41,Male,Yes,No,No,Yes,Yes,No,No,Yes,No,Yes,No,Yes,Yes,No,Positive
3,45,Male,No,No,Yes,Yes,Yes,Yes,No,Yes,No,Yes,No,No,No,No,Positive
4,60,Male,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Positive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
515,39,Female,Yes,Yes,Yes,No,Yes,No,No,Yes,No,Yes,Yes,No,No,No,Positive
516,48,Female,Yes,Yes,Yes,Yes,Yes,No,No,Yes,Yes,Yes,Yes,No,No,No,Positive
517,58,Female,Yes,Yes,Yes,Yes,Yes,No,Yes,No,No,No,Yes,Yes,No,Yes,Positive
518,32,Female,No,No,No,Yes,No,No,Yes,Yes,No,Yes,No,No,Yes,No,Negative
519,42,Male,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Negative

In [26]:
df.head(2)#ilk iki satırı gösterir

,Age,Gender,Polyuria,Polydipsia,sudden weight loss,weakness,Polyphagia,Genital thrush,visual blurring,Itching,Irritability,delayed healing,partial paresis,muscle stiffness,Alopecia,Obesity,class
0,40,Male,No,Yes,No,Yes,No,No,No,Yes,No,Yes,No,Yes,Yes,Yes,Positive
1,58,Male,No,No,No,Yes,No,No,Yes,No,No,No,Yes,No,Yes,No,Positive

In [27]:
df.tail(3)#son üç satırı gösterir

,Age,Gender,Polyuria,Polydipsia,sudden weight loss,weakness,Polyphagia,Genital thrush,visual blurring,Itching,Irritability,delayed healing,partial paresis,muscle stiffness,Alopecia,Obesity,class
517,58,Female,Yes,Yes,Yes,Yes,Yes,No,Yes,No,No,No,Yes,Yes,No,Yes,Positive
518,32,Female,No,No,No,Yes,No,No,Yes,Yes,No,Yes,No,No,Yes,No,Negative
519,42,Male,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Negative

In [28]:
df.shape #satır ve sütun sayısını verir

(520, 17)

In [29]:
df.info #veri seti ile ilgili bilgililer verir

<bound method DataFrame.info of      Age  Gender Polyuria Polydipsia sudden weight loss weakness Polyphagia  \
0     40    Male       No        Yes                 No      Yes         No
1     58    Male       No         No                 No      Yes         No
2     41    Male      Yes         No                 No      Yes        Yes
3     45    Male       No         No                Yes      Yes        Yes
4     60    Male      Yes        Yes                Yes      Yes        Yes
..   ...     ...      ...        ...                ...      ...        ...
515   39  Female      Yes        Yes                Yes       No        Yes
516   48  Female      Yes        Yes                Yes      Yes        Yes
517   58  Female      Yes        Yes                Yes      Yes        Yes
518   32  Female       No         No                 No      Yes         No
519   42    Male       No         No                 No       No         No

    Genital thrush visual blurring Itching Irritability delayed healing  \
0               No              No     Yes           No             Yes
1               No             Yes      No           No              No
2               No              No     Yes           No             Yes
3              Yes              No     Yes           No             Yes
4               No             Yes     Yes          Yes             Yes
..             ...             ...     ...          ...             ...
515             No              No     Yes           No             Yes
516             No              No     Yes          Yes             Yes
517             No             Yes      No           No              No
518             No             Yes     Yes           No             Yes
519             No              No      No           No              No

    partial paresis muscle stiffness Alopecia Obesity     class
0                No              Yes      Yes     Yes  Positive
1               Yes               No      Yes      No  Positive
2                No              Yes      Yes      No  Positive
3                No               No       No      No  Positive
4               Yes              Yes      Yes     Yes  Positive
..              ...              ...      ...     ...       ...
515             Yes               No       No      No  Positive
516             Yes               No       No      No  Positive
517             Yes              Yes       No     Yes  Positive
518              No               No      Yes      No  Negative
519              No               No       No      No  Negative

[520 rows x 17 columns]>

In [30]:
df.ndim #veri setinin boyutunu verir

2

In [31]:
df.size #veri setinde kaç adet veri olduğunu gösterir

8840